### ISSUE TITLE
Vision shooter speed

### ISSUE THREAD

**Issue by bricktrooper** [team4015/FRC-Robot-2022-Rapid-React#35]
Once aligned with the target, vision should calculate the shooter speed needed to get the ball in.  When the vision aiming command is running, it will have control over the drivetrain for alignment purposes, and the shooter for charging it up to a certain speed.  The vision aiming command take over whenever the operator presses the button.  When the button is released, the drivetrain control is returned to the driver, and the shooter will stop charging up.

Vision does not hijack the conveyor, which is essentially the shooter trigger.  So while the operator holds down the vision, the robot will stay aligned and the shooter will spin.  This means that while holding down vision, we simply press the conveyor feed button to shoot balls.  Basically to shoot: hold down vision + use conveyor.  Then release vision when done shooting to regain manual control of the drivetrain and shooter.

**Comment by bricktrooper** [comment]
These are just notes on how the vision + shooter + aiming controls might work.  Up to you guys how you wanna implement it but I just wanted to write it down here.

**Comment by jjieshenwang** [comment]
i got something to calculate the speed, but ill think about the rest tmr
